name: JoDija_tamplites
description: A new Flutter project.
version: 0.0.1
homepage: page 

environment:
    sdk: '>=3.0.6 <4.0.0'

    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  path_provider: ^2.0.6
  animate_do: ^2.1.0
  flutter_animate: ^4.1.0
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.6
  flutter_bloc: ^8.1.1
  provider: ^6.0.3
   # For modern web interoperability
  dio: ^5.4.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.7
  
  freezed_annotation: ^1.1.0
  sqflite: ^2.0.0+4
  
  sqflite_common_ffi: ^2.3.4+4
  get_it: ^7.2.0
  
  # url_strategy: ^0.2.0
  # web: ^0.3.0  # Latest version for web platform APIs
  # js_interop: ^0.0.1  # For JavaScript interop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0  # Required for js_interop code generation
    # For generating JS interop bindings

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
 

  # To add assets to your package, add an assets section, like this:
assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
